version: "3.7"

services:
  app:
    build: .
    volumes:
      - <path-to-klaytn-dex-contracts>/deployments:/app/deployments
    environment:
      DEX_CONTRACT_DEPLOYMENT_DIR: /app/deployments
      DEX_NETWORK_NAME: baobab
      DEX_GRAPHNODE_RPC_URL:
      DEX_GRAPHNODE_IPFS_URL:
      DEX_VERSION_LABEL: 0.0.1
