name: Build & public container image
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  REGISTRY: docker.io
  IMAGE_ORG: klaytn
  IMAGE_NAME: klaytn-dex-subgraphs

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_ORG }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
